### ISSUE TITLE
WF maven-publish isn't triggered on push to master

### ISSUE THREAD

**Issue by uwehdaub** [metro-digital-inner-source/.github#5]
WF maven-publish isn't triggered on push to master

**Comment by uwehdaub** [comment]
The following won't work, because the variable `$default-branch` don't exists.
But it also doesn't create an error to use it!

```yaml
on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

```

**Comment by uwehdaub** [comment]
Also the following won't work:

```yaml
on:
  workflow_dispatch:
  push:
    branches: [ ${{ github.event.repository.default_branch }} ]
  pull_request:
    branches: [ ${{ github.event.repository.default_branch }} ]
```

The expression `${{ github.event.repository.default_branch }}` if it is used inside `jobs`, but it doesn't seem to exists and can't be evaluated in `on`.

**Comment by uwehdaub** [comment]
The currently best available solution is, to list the possible default branches explicitly:

```yaml
on:
  workflow_dispatch:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
```

It is pretty unlikely, that somebody uses both `master` and `main` in the same repository.
